// components/partners.vue
<template>
  <section class="partners" data-scroll-to="partners">
    <div class="partners__wrapper">
      <h3 class="partners__header">{{ $t("partners.header") }}</h3>
      <spacer />
    </div>
    <ul class="partners__list">
      <li class="partners__list_item" v-for="partner in formatted_partners" :key="partner.slug">
        <img
          class="partners__logo"
          :src="require(`../assets/icons/partners/${partner.slug}.svg`)"
          :alt="partner.name"
        />
      </li>
    </ul>
  </section>
</template>

<script lang="ts">
import Spacer from "./common/spacer.vue";
import ServiceItem from "./services/service-item.vue";

export default {
  components: {
    Spacer,
    ServiceItem
  },
  data() {
    return {
      partners: [
        "Siemens",
        "Rockwell Automation",
        "Asem",
        "Rittal",
        "Schneider",
        "Danfoss",
        "ABB",
        "Zanardo",
        "Yaskawa",
        "Woehner",
        "Italweber"
      ]
    };
  },
  computed: {
    formatted_partners: function() {
      return this.partners.map(p => ({
        name: p,
        slug: p
          .toLowerCase()
          .trim()
          .replace(" ", "_")
      }));
    }
  }
};
</script>

<style lang="scss" scoped>
.partners__wrapper {
  @include section-wrapper;
}
.partners__header {
  @include section-header;

  text-align: center;
}
.partners__list {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  margin-top: -60px;
}
.partners__list__item {
}
.partners__logo {
  height: 50px;
  margin: 30px 30px;
  max-width: calc(100% - 60px);
}
</style>

// components/Partners/Partners.tsx
import React, { useCallback, useEffect, useRef } from 'react'
import classNames from 'classnames';
import { useTranslation } from 'next-i18next';

const partners = [
  { name: 'ABB', src: '/partners/abb.svg', customClass: 'max-w-[150px]' },
  { name: 'asem', src: '/partners/asem.svg' },
  { name: 'danfoss', src: '/partners/danfoss.svg' },
  { name: 'italweber', src: '/partners/italweber.svg' },
  { name: 'rittal', src: '/partners/rittal.svg', customClass: 'max-w-[102px]' },
  { name: 'rockwell-automation', src: '/partners/rockwell-automation.svg' },
  { name: 'schneider-electric', src: '/partners/schneider-electric.svg' },
  { name: 'siemens', src: '/partners/siemens.svg' },
  { name: 'wöhner', src: '/partners/wöhner.svg' },
  { name: 'yaskawa', src: '/partners/yaskawa.svg' },
  { name: 'zanardo', src: '/partners/zanardo.svg' },
]

export const Partners = () => {
  const { t } = useTranslation(['home']);

  return (
    <section id="partners">
      <div className="container py-20">
        <h2 className="mb-16 text-4xl text-medium sm:text-center">
          {t('partners.title1')} <span className="text-dielle">{t('home:partners.title2')}</span>
        </h2>

        <div className="flex flex-wrap items-center justify-center space-x-12 -my-6">
          {partners.map(({ name, src, customClass }) => (
            <img
              className={classNames('max-w-[200px] my-6', customClass)}
              key={src}
              src={src}
              alt={name}
            />)
          )}
        </div>
      </div>
    </section>
  )
};
