// components/footer.vue
<template>
  <footer class="footer">
    <div class="footer__wrapper">
      <img class="footer__logo" src="~assets/icons/logo-white.svg" />
      <div class="footer__entries">
        <div class="footer__entry">
          <h4 class="footer__entry__header">Contatti</h4>
          <div class="footer__entry__text">
            Via Galileo Galilei 1, Galliera Veneta (PD) 35015
            <br />Tel: 049 9440586
            <br />Fax: 049 9443414
            <br />Mail:
            <a
              href="mailto:info@dielleimpianti.it"
              alt="Contattaci via mail"
            >info@dielleimpianti.it</a>
            <br />Partita IVA: 02474770282
          </div>
        </div>
        <div class="footer__entry">
          <h4 class="footer__entry__header">Lavora con noi</h4>
          <div class="footer__entry__text">
            Clicca
            <a href="mailto:info@dielleimpianti.it" alt="Inviaci il curriculum">qui</a> per inviare il tuo curriculum
          </div>
        </div>
      </div>
    </div>
  </footer>
</template>

<script lang="ts">
export default {};
</script>

<style lang="scss" scoped>
.footer {
  @include bg-gradient;

  width: 100%;
}

.footer__wrapper {
  @include section-wrapper;

  padding: 30px;
  display: flex;
  justify-content: space-between;
}

.footer__logo {
  width: 180px;
  height: 180px;
}

.footer__entries {
  margin-top: 30px;
}
.footer__entry {
  margin-bottom: 30px;

  &__header {
    font-size: medium;
    color: white;
    margin-bottom: 5px;
  }
  &__text {
    @include section-text;

    color: white;
    line-height: 18px;
    text-decoration: none;

    a {
      color: white;
      // text-decoration: none;
    }
  }
}
</style>

// components/Footer/Footer.tsx
import React from "react";
import { useTranslation } from "next-i18next";

export const Footer = () => {
  const { t } = useTranslation(['common']);

  return (
    <footer>
      <div className="container py-20">
        <hr />
        <div className="py-5 flex justify-between">
          <img
            className="max-w-[150px] opacity-90"
            src="/logo-black.svg"
            alt={`${t('companyName')} - ${t('companyMotto')}`}
          />

          <div>
            <h3 className="font-medium">Azienda</h3>
            <ul>
              <li><a className="hover:underline" href="#">Soluzioni</a></li>
              <li><a className="hover:underline" href="#">Su di noi</a></li>
              <li><a className="hover:underline" href="#">Settori</a></li>
              <li><a className="hover:underline" href="#">Parters</a></li>
              <li><a className="hover:underline" href="#">Contattaci</a></li>
            </ul>
          </div>

          <div>
            <h3 className="font-medium">{t('companyLegalName')}</h3>
            <p>
              Via Galileo Galilei 1, <br />
              Galliera Veneta, PD <br />
              35015, Italia
            </p>
            <h3 className="mt-2 font-medium">Partita IVA</h3>
            <p>02474770282</p>
          </div>

          <div>
            <h3 className="font-medium">Contatti</h3>
            <ul>
              <li>Email: <a className="underline font-light" href={`mailto:${t('companyEmail')}`}>{t('companyEmail')}</a></li>
              <li>Tel: <a className="underline font-light" href={`tel:${t('companyPhone')}`}>{t('companyPhone')}</a></li>
              <li>Fax: <a className="underline font-light" href={`fax:${t('companyFax')}`}>{t('companyFax')}</a></li>
            </ul>

            <h3 className="mt-2 font-medium">Lavora con noi</h3>
            <p></p>
          </div>

        </div>
        <hr />
        <div className="py-5 font-medium">
          &#169; {t('companyLegalName')} {new Date().getFullYear()}. All Rights Reserved.
        </div>
      </div>
    </footer>
  );
}
